### PR TITLE
Feature/#22 brainstorming the router setup for the advertisment feature

### LINKED ISSUE #22: Brainstorming the router setup for the Advertisement feature

### PR DESCRIPTION
**Pull request by FanniFelfoldi**
# Feature/Change Description

create:
-advertisement module
- advertisement-container.component
-advertisement-list.component
-ditails.component

_Describe changes made here, link to any issue that is addressed_

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

### CODE REVIEW

**Comment by FanniFelfoldi** [comment]
Ho tolto lazy loading per AdvertismentModule :)

**Review by pc-codingavision — CHANGES_REQUESTED** [review]
@FanniFelfoldi please, review the comments. Thanks 
---  
- I believe that it is missing the mapping in the app-routing
- The branch is not update-to-date with develop

**Comment by FanniFelfoldi** [comment]
Ciao Piero, 
develop in my branch now is updated
I corrected the ruoting map, now mapping is inside app-routing.module

**Comment by pc-codingavision** [comment]
@FanniFelfoldi I refactored the advertisement routing, we will talk about the why during the lesson.

**Pull request merged**
